name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable corepack (Yarn Berry)
        run: corepack enable

      - name: Install dependencies
        working-directory: minimaui
        run: yarn install --immutable

      - name: Typecheck
        working-directory: minimaui
        run: yarn typecheck

      - name: Lint
        working-directory: minimaui
        run: yarn lint

      - name: Test
        working-directory: minimaui
        run: yarn test

      - name: Build
        working-directory: minimaui
        run: yarn build

