name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: minimaui/yarn.lock
          registry-url: https://registry.npmjs.org

      - name: Use Corepack Yarn 3.2.1
        run: |
          corepack enable
          corepack prepare yarn@3.2.1 --activate

      - name: Install dependencies
        working-directory: minimaui
        run: yarn install --immutable

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          publish: yarn build && yarn release
          cwd: minimaui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
